import json
from collections import Counter


INPUT_FILE = "sample_input.json"
OUTPUT_FILE = "security_report.json"


# Demo threat intelligence data
KNOWN_SUSPICIOUS_IPS = {
    "45.155.205.233"
}

KNOWN_SUSPICIOUS_DOMAINS = {
    "unknown-login.com"
}


# Project-defined thresholds
REPEATED_ACTIVITY_THRESHOLD = 3
ANOMALY_FAILED_LOGIN_THRESHOLD = 3


def load_logs(filename):
    """Load security events from JSON."""

    try:
        with open(filename, "r") as file:
            return json.load(file)

    except FileNotFoundError:
        print(f"[ERROR] File not found: {filename}")
        return []

    except json.JSONDecodeError:
        print(f"[ERROR] Invalid JSON format: {filename}")
        return []


def count_ip_activity(logs):
    """Count events generated by each IP."""

    return Counter(
        log.get("source_ip", "unknown")
        for log in logs
    )


def count_failed_logins(logs):
    """Count failed login attempts per IP."""

    failed_events = [
        log for log in logs
        if (
            log.get("event_type") == "login"
            and log.get("status") == "failed"
        )
    ]

    return Counter(
        log.get("source_ip", "unknown")
        for log in failed_events
    )


def enrich_event(event):
    """Add threat and contextual information to an event."""

    ip = event.get("source_ip", "")
    domain = event.get("domain", "")
    device = event.get("device_type", "Unknown")

    enriched = event.copy()

    enriched["ioc_match"] = ip in KNOWN_SUSPICIOUS_IPS

    enriched["domain_match"] = (
        domain in KNOWN_SUSPICIOUS_DOMAINS
    )

    enriched["device_type"] = device

    return enriched


def calculate_risk_score(event, ip_activity):
    """Calculate a simple rule-based risk score."""

    score = 0
    reasons = []

    ip = event.get("source_ip", "")
    domain = event.get("domain", "")

    # Suspicious IP
    if ip in KNOWN_SUSPICIOUS_IPS:
        score += 3
        reasons.append("Suspicious IP")

    # Unknown/suspicious domain
    if domain in KNOWN_SUSPICIOUS_DOMAINS:
        score += 2
        reasons.append("Unknown or suspicious domain")

    # Repeated activity
    if ip_activity.get(ip, 0) >= REPEATED_ACTIVITY_THRESHOLD:
        score += 4
        reasons.append("Repeated activity")

    # Failed login
    if event.get("status") == "failed":
        score += 1
        reasons.append("Failed login")

    if score >= 7:
        risk_level = "High"
    elif score >= 4:
        risk_level = "Medium"
    else:
        risk_level = "Low"

    return score, risk_level, reasons


def detect_anomaly(event, ip_activity, failed_activity):
    """Detect unusual behavior."""

    ip = event.get("source_ip", "")

    reasons = []

    if failed_activity.get(ip, 0) >= ANOMALY_FAILED_LOGIN_THRESHOLD:
        reasons.append("Repeated failed login attempts")

    if ip_activity.get(ip, 0) > 5:
        reasons.append("Unusual login activity")

    return len(reasons) > 0, reasons


def process_logs(logs):
    """Process logs through enrichment, scoring, and anomaly detection."""

    ip_activity = count_ip_activity(logs)
    failed_activity = count_failed_logins(logs)

    processed_events = []

    for event in logs:

        enriched_event = enrich_event(event)

        score, risk_level, score_reasons = calculate_risk_score(
            enriched_event,
            ip_activity
        )

        anomaly, anomaly_reasons = detect_anomaly(
            enriched_event,
            ip_activity,
            failed_activity
        )

        enriched_event["risk_score"] = score
        enriched_event["risk_level"] = risk_level
        enriched_event["risk_reasons"] = score_reasons

        enriched_event["anomaly"] = anomaly
        enriched_event["anomaly_reasons"] = anomaly_reasons

        processed_events.append(enriched_event)

    return processed_events


def generate_report(events):
    """Generate final security report."""

    high_risk = [
        event
        for event in events
        if event["risk_level"] == "High"
    ]

    anomalies = [
        event
        for event in events
        if event["anomaly"]
    ]

    report = {
        "project": "AI Security Data Processing Engine",
        "total_events_processed": len(events),
        "high_risk_events": len(high_risk),
        "anomalous_events": len(anomalies),
        "events": events
    }

    return report


def save_report(report, filename):
    """Save final report as JSON."""

    with open(filename, "w") as file:
        json.dump(report, file, indent=4)

    print(f"[+] Security report saved to {filename}")


def main():

    print("=" * 55)
    print(" AI SECURITY DATA PROCESSING ENGINE")
    print("=" * 55)

    print("\n[1] Loading security logs...")

    logs = load_logs(INPUT_FILE)

    if not logs:
        print("[!] No logs available.")
        return

    print(
        f"[+] {len(logs)} events loaded."
    )

    print("\n[2] Processing events...")

    processed_events = process_logs(logs)

    print("[+] Threat enrichment completed.")
    print("[+] Risk scoring completed.")
    print("[+] Anomaly detection completed.")

    print("\n[3] Generating security report...")

    report = generate_report(processed_events)

    save_report(
        report,
        OUTPUT_FILE
    )

    print("\n[+] Processing Summary")
    print(
        f"Total events: "
        f"{report['total_events_processed']}"
    )
    print(
        f"High-risk events: "
        f"{report['high_risk_events']}"
    )
    print(
        f"Anomalous events: "
        f"{report['anomalous_events']}"
    )


if __name__ == "__main__":
    main()