import json
from collections import Counter


INPUT_FILE = "sample_logs.json"
OUTPUT_FILE = "anomaly_report.json"


# Project-defined detection thresholds
UNUSUAL_LOGIN_THRESHOLD = 5
FAILED_LOGIN_THRESHOLD = 3
ABNORMAL_IP_THRESHOLD = 10


def load_logs(filename):
    """Load security logs from JSON."""

    try:
        with open(filename, "r") as file:
            return json.load(file)

    except FileNotFoundError:
        print(f"[ERROR] File not found: {filename}")
        return []

    except json.JSONDecodeError:
        print(f"[ERROR] Invalid JSON format: {filename}")
        return []


def count_ip_activity(logs):
    """Count total events generated by each IP."""

    return Counter(
        log.get("source_ip", "unknown")
        for log in logs
    )


def count_failed_logins(logs):
    """Count failed login attempts for each IP."""

    failed_logins = [
        log for log in logs
        if (
            log.get("event_type") == "login"
            and log.get("status") == "failed"
        )
    ]

    return Counter(
        log.get("source_ip", "unknown")
        for log in failed_logins
    )


def detect_anomalies(logs):
    """Detect unusual login and IP behavior."""

    ip_activity = count_ip_activity(logs)
    failed_activity = count_failed_logins(logs)

    anomalies = []

    # Detect abnormal behavior for each IP
    all_ips = set(ip_activity.keys())

    for ip in all_ips:

        total_events = ip_activity[ip]
        failed_logins = failed_activity.get(ip, 0)

        reasons = []

        # Rule 1: Unusual login attempts
        if total_events > UNUSUAL_LOGIN_THRESHOLD:
            reasons.append(
                f"Unusual login activity "
                f"({total_events} attempts)"
            )

        # Rule 2: Repeated failed access
        if failed_logins >= FAILED_LOGIN_THRESHOLD:
            reasons.append(
                f"Repeated failed access "
                f"({failed_logins} failures)"
            )

        # Rule 3: Abnormal IP behavior
        if total_events >= ABNORMAL_IP_THRESHOLD:
            reasons.append(
                f"Abnormal IP activity "
                f"({total_events} events)"
            )

        if reasons:

            anomalies.append({
                "source_ip": ip,
                "total_events": total_events,
                "failed_logins": failed_logins,
                "anomaly": True,
                "reasons": reasons
            })

    return anomalies


def save_report(anomalies, filename):
    """Save anomaly results to JSON."""

    report = {
        "total_anomalous_ips": len(anomalies),
        "anomalies": anomalies
    }

    with open(filename, "w") as file:
        json.dump(report, file, indent=4)

    print(
        f"[+] Anomaly report saved to {filename}"
    )


def main():

    print(
        "[*] Starting Cybersecurity Anomaly Detector..."
    )

    logs = load_logs(INPUT_FILE)

    if not logs:
        print("[!] No logs available.")
        return

    anomalies = detect_anomalies(logs)

    save_report(
        anomalies,
        OUTPUT_FILE
    )

    print("\n[+] Detected Anomalies:")

    if not anomalies:
        print("No suspicious behavior detected.")
        return

    for anomaly in anomalies:

        print(
            f"\nIP: {anomaly['source_ip']}"
        )

        print(
            f"Total Events: "
            f"{anomaly['total_events']}"
        )

        print(
            f"Failed Logins: "
            f"{anomaly['failed_logins']}"
        )

        for reason in anomaly["reasons"]:
            print(f"- {reason}")


if __name__ == "__main__":
    main()